import json
import os
import sys
import requests


def post_pr_comment(repo, pr_number, token, message):
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }

    payload = {"body": message}

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code != 201:
        print(f"Failed to post comment: {response.text}")
        sys.exit(1)

    print("SUCCESS: Comment posted to PR")


def main():
    repo = os.environ["GITHUB_REPOSITORY"]
    pr_number = os.environ["PR_NUMBER"]
    token = os.environ["GITHUB_TOKEN"]

    with open("ai/reasoning/ai_review.json", "r") as f:
        review = json.load(f)

    message = f"""
## 🤖 AI Terraform Review

**Risk Level:** `{review['risk_level']}`

### 🔍 Reasons
{chr(10).join(f"- {r}" for r in review['reasons'])}

### 💬 Review Comments
{chr(10).join(f"- {c}" for c in review['review_comments'])}

---
_Automated review generated by AI Terraform Reviewer_
"""

    post_pr_comment(repo, pr_number, token, message)


if __name__ == "__main__":
    main()
